### ISSUE TITLE
EzApiCreatorFails on linux host 

### ISSUE THREAD

**Issue by luky92** [rmcrackan/AudibleApi#51]
EzApiCreator Fails on linux with thiis exception:
Exception thrown Mrssage: No matching result page type Stacktrace:    at AudibleApi.Authentication.LoginResultRunner.getResultsPageAsync(Authenticate authenticate, Dictionary2 inputs, HttpResponseMessage response) in C:\Users\PC\Source\Repos\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 48
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, Dictionary2 inputs, HttpMethod method, String url) in C:\Users\PC\Source\Repos\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 26
   at AudibleApi.Authentication.CredentialsPage.SubmitAsync(String email, String password) in C:\Users\PC\Source\Repos\AudibleApi\AudibleApi\Authentication\CredentialsPage.cs:line 22
   at AudibleApi.Authentication.Authenticate.SubmitCredentialsAsync(String email, String password) in C:\Users\PC\Source\Repos\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 85
   at AudibleApi.Authentication.Authenticate.SubmitCredentialsAsync(Locale locale, String deviceName, String email, String password) in C:\Users\PC\Source\Repos\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 56
   at AudibleApi.EzApiCreator.loginEmailPasswordAsync(Locale locale, ILoginCallback responder, String email, String password) in C:\Users\PC\Source\Repos\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.LoginCallback.cs:line 51
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Users\PC\Source\Repos\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.LoginCallback.cs:line 46
   at AudibleApi.EzApiCreator.GetApiAsync(ILoginCallback loginCallback, Locale locale, String identityFilePath, String jsonPath) in C:\Users\PC\Source\Repos\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.LoginCallback.cs:line 29

**Comment by luky92** [comment]
after furter invastigation it turns oyt that it only happens if the program usind the liblary is in single file publish mode
